import { DiagnosisQuestion, Language, MRPData } from "./types";

export const MAPBOX_TOKEN =
  "pk.eyJ1IjoiZmVycGFpeGFvIiwiYSI6ImNtbDYxcWxmMjBhN3QzbG9qZ2hxN3piMnoifQ.5-naVFuxtLiOLT0qiuOtkQ";

export const COLORS = {
  teal: "#006A71",
  offWhite: "#F8F8F4",
  coral: "#FF7D6B",
  mustard: "#EAA823",
};

// ⚡ PROMPTS DESIDRATADOS (Ultraleves para velocidade máxima) ⚡
// A doutrina pesada (Persona, Lore, Regras JSON) agora vive APENAS no AWS Bedrock.
// O frontend envia apenas os dados em tempo real.

export const getSystemInstruction = (
  lang: Language,
  city?: string,
  profile?: string,
  rawAnswers?: Record<string, number>,
  portalContext?: string,
) => {
  // APENAS CONTEXTO DO USUÁRIO — sem regras de formato, persona ou instruções de conteúdo.
  // A Doutrina Mestre e knowledge base (bibliotecacult1.json) vivem no AWS Bedrock Agent.
  return `CIDADE: ${city || "N/A"}
PERFIL: ${profile || "N/A"}
SCORES: ${JSON.stringify(rawAnswers || {})}
PORTAL: ${portalContext || "Geral"}
IDIOMA: ${lang.toUpperCase()}`;
};

export const getPortalQuestionInstruction = (lang: Language, city: string, portal: string, mrpData: MRPData) => {
  return `CIDADE: ${city}
PORTAL: ${portal}
IDIOMA: ${lang.toUpperCase()}`;
};

export const getGemContextInstruction = (
  lang: Language,
  city: string,
  portal: string,
  mrpData: MRPData,
  userPreference: string,
) => {
  return `CIDADE: ${city}
PORTAL: ${portal}
PERFIL: ${mrpData.profile || "N/A"}
MENSAGEM_USUARIO: "${userPreference}"
IDIOMA: ${lang.toUpperCase()}`;
};

// --- TODO O CONTEÚDO VISUAL E PERGUNTAS CONTINUAM INTACTOS ---
export const CONTENT = {
  pt: {
    subtitle: "inteligência cultural",
    enterBtn: "Entrar",
    signOutBtn: "Sair",
    myMapsBtn: "Minhas Cartografias",
    landingTitle: "Existe uma Cidade para o seu agora.",
    landingDesc: "A curadoria definitiva de gemas baseada na sua presença.",
    loginWarningDesc: "Sua cartografia é efêmera. Faça login para salvar.",
    startBtn: "Meus lugares na cidade",
    analyzing: "Percebendo seu ritmo...",
    resultTitle: "Diagnóstico de Presença",
    comingSoon: "Em breve",
    portalTitle: "Escolha seu Portal",
    inputPlaceholder: "Escreva o bairro, Sim/Não...",
    diagnosisTitle: "Status de Presença",
    poeticTitle: "Observação / Ritual",
    historyTitle: "Minhas Cartografias",
    viewList: "Lista",
    viewMap: "Mapa",
    loginWarning: "Identifique-se para acessar esta cartografia.",
    loginWallMessage: "Seu mapa está pronto. Faça login para revelar suas Gems e seu diagnóstico completo.",
    loginBtn: "Acessar Cartografia",
    revealMapBtn: "Revelar meu Mapa",
    shareArchetypeBtn: "Compartilhar meu Arquétipo",
    continueNoSave: "Continuar sem salvar",
    shareText: "Meu status Cult AI:",
    shareGems: "Gemas recomendadas:",
    shareCall: "Descubra o seu:",
    copied: "Copiado!",
    saveCartographyBtn: "Salvar Cartografia",
    termsBtn: "TERMOS E PRIVACIDADE",
    termsTitle: "Termos",
    termsText: "Dados anônimos para pesquisa cultural.",
    editMapBtn: "Ver Detalhes",
    gemSectionTitle: "REVELAÇÕES",
    saveToMyCult: "Salvar Gemas",
    shareMap: "Compartilhar",
    feedbackTitle: "Feedback",
    feedbackRating: "Nota:",
    feedbackComment: "Comentário:",
    feedbackSubmit: "Enviar",
    feedbackSuccess: "Valeu!",
    revelingGems: "Filtrando gemas...",
    retumingSession: "Retomando",
    deleteConfirm: "Deseja apagar?",
    profileTitle: "Você é:",
    visitor: "Visitante",
    resident: "Residente",
    gemInteractionPlaceholder: "Algum detalhe a mais? Se quiser outras gemas, fale suas preferências.",
    loginModalTitle: "Faça seu login",
    loginModalDesc: "e desbloqueie as gemas 💎",
    continueGoogle: "Google Login",
    securePrivate: "Seguro e Privado",
    changePortalBtn: "Trocar Portal",
    sourceTitle: "Fontes:",
    pillars: {
      body: "Corpo",
      territory: "Território",
      identity: "Identidade",
      other: "O Outro",
      space: "Espaço",
    },
    questions: [
      {
        id: "body_1",
        category: "body",
        label: "CAOS",
        question: "Qual seu nível de tolerância para o caos hoje?",
        lowLabel: "Paz absoluta",
        highLabel: "Quero me perder",
      },
      {
        id: "territory_1",
        category: "territory",
        label: "TERRITÓRIO",
        question: "Você se sente pertencente ao lugar que está agora?",
        lowLabel: "Estranha",
        highLabel: "Em Casa",
      },
      {
        id: "identity_1",
        category: "identity",
        label: "IDENTIDADE",
        question: "Ver e ser vista ou modo incógnito?",
        lowLabel: "Incógnito",
        highLabel: "Ver",
      },
      {
        id: "other_1",
        category: "other",
        label: "CONTATO",
        question: "Disposição para falar com estranhos?",
        lowLabel: "Zero",
        highLabel: "Muita",
      },
      {
        id: "space_1",
        category: "space",
        label: "ESTÍMULO",
        question: "Som ideal agora: silêncio ou batida?",
        lowLabel: "Silêncio",
        highLabel: "Batida",
      },
    ],
    feedback: {
      body: { low: "Ritmo lento.", high: "Ativo." },
      territory: { low: "Fora de casa.", high: "Familiar." },
      identity: { low: "Discreto.", high: "Exposto." },
      other: { low: "Fechado.", high: "Aberto." },
      space: { low: "Calmo.", high: "Intense." },
    },
    portals: [
      "🌿 Natureza",
      "🎈 Eventos",
      "🧿 Intelectual / Cult",
      "✨ Luxo Escondido",
      "🧙‍♀️ Espiritual",
      "🎨 Criativo / Lifestyle",
      "🍽️ Gastronomia",
      "🏛️ Cultura",
      "❤️ Sexy & Romântico",
      "🎒 Viagem Curta",
      "👨‍👩‍👧‍👦 Família",
      "🚩 Ciladas da Cidade",
    ],
    legendIntrospective: "Introspectivo",
    legendSocial: "Social",
    legendCreative: "Criativo",
    premiumNewMapBtn: "Quero um novo mapa completo!",
    premiumFullMapBtn: "Mapa completo de 3 meses — R$ 89,90",
    sessionsUsed: "sessões usadas",
    buyMoreBtn: "Comprar mais",
    paymentConfirmed: "Pagamento confirmado! 🎉",
    paymentNewSession: "Sua nova sessão já está disponível.",
    paymentActivating: "Seu acesso está sendo ativado. Aguarde alguns segundos...",
    paymentCanceled: "Pagamento cancelado",
    paymentTryAgain: "Você pode tentar novamente quando quiser.",
  },
  en: {
    subtitle: "cultural intelligence",
    enterBtn: "Login",
    signOutBtn: "Logout",
    myMapsBtn: "My Maps",
    landingTitle: "A Gem for your now.",
    landingDesc: "The ultimate gem curation based on your presence.",
    loginWarningDesc: "Your map is temporary. Log in to save it.",
    startBtn: "My places in the city",
    analyzing: "Sensing rhythm...",
    resultTitle: "Presence Diagnosis",
    comingSoon: "Soon",
    portalTitle: "Choose your Portal",
    inputPlaceholder: "Type neighborhood, Yes/No...",
    diagnosisTitle: "Presence Status",
    poeticTitle: "Observation / Ritual",
    historyTitle: "My Maps",
    viewList: "List",
    viewMap: "Map",
    loginWarning: "Identify yourself to access this map.",
    loginWallMessage: "Your map is ready. Sign in to reveal your Gems and full diagnosis.",
    loginBtn: "Access Map",
    revealMapBtn: "Reveal my Map",
    shareArchetypeBtn: "Share my Archetype",
    continueNoSave: "Continue without saving",
    shareText: "My Cult AI status:",
    shareGems: "Recommended gems:",
    shareCall: "Discover yours:",
    copied: "Copied!",
    saveCartographyBtn: "Save Map",
    termsBtn: "TERMS AND PRIVACY",
    termsTitle: "Terms",
    termsText: "Anonymous data for research.",
    editMapBtn: "Details",
    gemSectionTitle: "REVELATIONS",
    saveToMyCult: "Save Gems",
    shareMap: "Share",
    feedbackTitle: "Feedback",
    feedbackRating: "Rate:",
    feedbackComment: "Comment:",
    feedbackSubmit: "Send",
    feedbackSuccess: "Thanks!",
    revelingGems: "Filtering gems...",
    retumingSession: "Resuming",
    deleteConfirm: "Delete?",
    profileTitle: "You are:",
    visitor: "Visitor",
    resident: "Resident",
    gemInteractionPlaceholder: "Any more details? If you want other gems, tell us your preferences.",
    loginModalTitle: "Sign in",
    loginModalDesc: "and unlock your gems 💎",
    continueGoogle: "Google Login",
    securePrivate: "Secure and Private",
    changePortalBtn: "Change Portal",
    sourceTitle: "Sources:",
    pillars: {
      body: "Body",
      territory: "Territory",
      identity: "Identity",
      other: "The Other",
      space: "Space",
    },
    questions: [
      {
        id: "body_1",
        category: "body",
        label: "CHAOS",
        question: "What's your tolerance for chaos today?",
        lowLabel: "Total peace",
        highLabel: "I want to get lost",
      },
      {
        id: "territory_1",
        category: "territory",
        label: "TERRITORY",
        question: "Do you feel you belong where you are?",
        lowLabel: "Stranger",
        highLabel: "At Home",
      },
      {
        id: "identity_1",
        category: "identity",
        label: "IDENTITY",
        question: "Seen or incognito?",
        lowLabel: "Incog",
        highLabel: "Seen",
      },
      {
        id: "other_1",
        category: "other",
        label: "CONTACT",
        question: "Open to talk to strangers?",
        lowLabel: "Zero",
        highLabel: "A lot",
      },
      {
        id: "space_1",
        category: "space",
        label: "STIMULUS",
        question: "Ideal sound right now?",
        lowLabel: "Quiet",
        highLabel: "Beat",
      },
    ],
    feedback: {
      body: { low: "Slow rhythm.", high: "Active." },
      territory: { low: "Far from home.", high: "Familiar." },
      identity: { low: "Discreet.", high: "Exposed." },
      other: { low: "Closed.", high: "Open." },
      space: { low: "Calm.", high: "Intense." },
    },
    portals: [
      "🌿 Nature",
      "🎈 Events",
      "🧿 Intellectual / Cult",
      "✨ Hidden Luxury",
      "🧙‍♀️ Spiritual",
      "🎨 Creative / Lifestyle",
      "🍽️ Gastronomy",
      "🏛️ Culture",
      "❤️ Sexy & Romantic",
      "🎒 Short Trip",
      "👨‍👩‍👧‍👦 Family",
      "🚩 City Pitfalls",
    ],
    legendIntrospective: "Introspective",
    legendSocial: "Social",
    legendCreative: "Creative",
    premiumNewMapBtn: "I want a new full map!",
    premiumFullMapBtn: "Full 3-month map — R$ 89.90",
    sessionsUsed: "sessions used",
    buyMoreBtn: "Buy more",
    paymentConfirmed: "Payment confirmed! 🎉",
    paymentNewSession: "Your new session is now available.",
    paymentActivating: "Your access is being activated. Please wait...",
    paymentCanceled: "Payment canceled",
    paymentTryAgain: "You can try again whenever you like.",
  },
  es: {
    subtitle: "inteligencia cultural",
    enterBtn: "Entrar",
    signOutBtn: "Salir",
    myMapsBtn: "Mis Mapas",
    landingTitle: "Una Ciudad para tu ahora.",
    landingDesc: "La curaduría definitiva de gemas basada en tu presencia.",
    loginWarningDesc: "Tu mapa é efímero. Regístrate para guardarlo.",
    startBtn: "Mis lugares en la ciudad",
    analyzing: "Sintiendo el ritmo...",
    resultTitle: "Diagnóstico de Presencia",
    comingSoon: "Pronto",
    portalTitle: "Elige tu Portal",
    inputPlaceholder: "Escriba el barrio, Sí/No...",
    diagnosisTitle: "Estatus de Presencia",
    poeticTitle: "Observación / Ritual",
    historyTitle: "Mis Mapas",
    viewList: "List",
    viewMap: "Mapa",
    loginWarning: "Identifícate para acceder a esta cartografía.",
    loginWallMessage: "Tu mapa está listo. Inicia sesión para revelar tus Gems y diagnóstico completo.",
    loginBtn: "Acceder Mapa",
    revealMapBtn: "Revelar mi Mapa",
    shareArchetypeBtn: "Compartir mi Arquetipo",
    continueNoSave: "Continuar sem guardar",
    shareText: "Mi estatus Cult AI:",
    shareGems: "Gemas recomendadas:",
    shareCall: "Descubra el tuyo:",
    copied: "¡Copiado!",
    saveCartographyBtn: "Guardar Mapa",
    termsBtn: "TÉRMINOS E PRIVACIDAD",
    termsTitle: "Términos",
    termsText: "Datos anónimos para investigación.",
    editMapBtn: "Detalles",
    gemSectionTitle: "REVELACIONES",
    saveToMyCult: "Guardar Gemas",
    shareMap: "Compartir",
    feedbackTitle: "Feedback",
    feedbackRating: "Nota:",
    feedbackComment: "Comentario:",
    feedbackSubmit: "Enviar",
    feedbackSuccess: "¡Gracias!",
    revelingGems: "Filtrando gemas...",
    retumingSession: "Retomando",
    deleteConfirm: "¿Borrar?",
    profileTitle: "Eres:",
    visitor: "Visitante",
    resident: "Residente",
    gemInteractionPlaceholder: "¿Algún detalle más? Si quieres otras gemas, cuéntanos tus preferencias.",
    loginModalTitle: "Inicia sesión",
    loginModalDesc: "y desbloquea las gemas 💎",
    continueGoogle: "Google Login",
    securePrivate: "Seguro e Privado",
    changePortalBtn: "Cambiar Portal",
    sourceTitle: "Fuentes:",
    pillars: {
      body: "Cuerpo",
      territory: "Territorio",
      identity: "Identidad",
      other: "El Otro",
      space: "Espacio",
    },
    questions: [
      {
        id: "body_1",
        category: "body",
        label: "CAOS",
        question: "¿Cuál es tu tolerancia al caos hoy?",
        lowLabel: "Paz absoluta",
        highLabel: "Quiero perderme",
      },
      {
        id: "territory_1",
        category: "territory",
        label: "TERRITORIO",
        question: "¿Te sientes perteneciente aqui?",
        lowLabel: "Extraño",
        highLabel: "En Casa",
      },
      {
        id: "identity_1",
        category: "identity",
        label: "IDENTIDAD",
        question: "¿Ver y ser visto o incógnito?",
        lowLabel: "Incógnito",
        highLabel: "Ver",
      },
      {
        id: "other_1",
        category: "other",
        label: "CONTACTO",
        question: "¿Abierto a hablar con extraños?",
        lowLabel: "Cero",
        highLabel: "Mucho",
      },
      {
        id: "space_1",
        category: "space",
        label: "ESTÍMULO",
        question: "Sonido ideal ahora:",
        lowLabel: "Paz",
        highLabel: "Ritmo",
      },
    ],
    feedback: {
      body: { low: "Ritmo lento.", high: "Activo." },
      territory: { low: "Lejos de casa.", high: "Familiar." },
      identity: { low: "Discreto.", high: "Expuesto." },
      other: { low: "Cerrado.", high: "Abierto." },
      space: { low: "Calmo.", high: "Intenso." },
    },
    portals: [
      "🌿 Naturaleza",
      "🎈 Eventos",
      "🧿 Intelectual / Cult",
      "✨ Lujo Escondido",
      "🧙‍♀️ Espiritual",
      "🎨 Creativo / Lifestyle",
      "🍽️ Gastronomía",
      "🏛️ Cultura",
      "❤️ Sexy & Romántico",
      "🎒 Escapada Corta",
      "👨‍👩‍👧‍👦 Familia",
      "🚩 Trampas de la Ciudad",
    ],
    legendIntrospective: "Introspectivo",
    legendSocial: "Social",
    legendCreative: "Creativo",
    premiumNewMapBtn: "¡Quiero un nuevo mapa completo!",
    premiumFullMapBtn: "Mapa completo de 3 meses — R$ 89,90",
    sessionsUsed: "sesiones usadas",
    buyMoreBtn: "Comprar más",
    paymentConfirmed: "¡Pago confirmado! 🎉",
    paymentNewSession: "Tu nueva sesión ya está disponible.",
    paymentActivating: "Tu acceso se está activando. Espera unos segundos...",
    paymentCanceled: "Pago cancelado",
    paymentTryAgain: "Puedes intentarlo de nuevo cuando quieras.",
  },
};

export const PORTAL_QUESTIONS: Record<string, DiagnosisQuestion[]> = {
  "🎈 eventos": [
    {
      id: "port_ev_1",
      category: "space",
      label: "ESTILO",
      question: "Trilha sonora da vez?",
      lowLabel: "Samba/Brasilidades",
      highLabel: "Eletrônico/Pop",
    },
    {
      id: "port_ev_2",
      category: "body",
      label: "TURNO",
      question: "Qual é o turno do corpo?",
      lowLabel: "Dia/Tarde",
      highLabel: "Noite/Madrugada",
    },
  ],
  "🍽️ gastronomia": [
    {
      id: "port_gas_1",
      category: "body",
      label: "FOCO",
      question: "O que a boca pede?",
      lowLabel: "Só Petiscos/Drinks",
      highLabel: "Jantar Completo",
    },
    {
      id: "port_gas_2",
      category: "identity",
      label: "DIETA",
      question: "Preferência do prato?",
      lowLabel: "Vegetariano/Vegano",
      highLabel: "Carnívoro/Churrasco",
    },
  ],
  "❤️ Sexy & Romântico": [
    {
      id: "port_rom_1",
      category: "identity",
      label: "CLIMA",
      question: "Como você está para esse date?",
      lowLabel: "Tímido/Intimista",
      highLabel: "Extrovertido/Agito",
    },
    {
      id: "port_rom_2",
      category: "space",
      label: "AMBIENTE",
      question: "Qual a iluminação ideal?",
      lowLabel: "Escurinho/Velas",
      highLabel: "Luz Natural",
    },
  ],
  "🧿 intelectual / cult": [
    {
      id: "port_cult_1",
      category: "space",
      label: "ESTÍMULO",
      question: "O que a mente quer absorver?",
      lowLabel: "Leitura/Pausa",
      highLabel: "Exposição/Visual",
    },
    {
      id: "port_cult_2",
      category: "other",
      label: "INTERAÇÃO",
      question: "Nível de socialização mental?",
      lowLabel: "Silêncio",
      highLabel: "Debate/Conversa",
    },
  ],
  "🌿 Natureza": [
    {
      id: "port_nat_1",
      category: "territory",
      label: "INTENSIDADE",
      question: "Que tipo de contato com a natureza?",
      lowLabel: "Parque Urbano",
      highLabel: "Trilha Selvagem",
    },
    {
      id: "port_nat_2",
      category: "body",
      label: "MOVIMENTO",
      question: "Qual o nível de atividade física?",
      lowLabel: "Contemplação",
      highLabel: "Esporte Intenso",
    },
  ],
  "✨ luxo escondido": [
    {
      id: "port_lux_1",
      category: "identity",
      label: "ESTÉTICA",
      question: "Qual a sua definição de luxo hoje?",
      lowLabel: "Clássico/Elegante",
      highLabel: "Design Moderno",
    },
    {
      id: "port_lux_2",
      category: "other",
      label: "VISIBILIDADE",
      question: "Qual o clima do lugar?",
      lowLabel: "Secreto/Exclusivo",
      highLabel: "Ver e ser visto",
    },
  ],
  "🧙‍♀️ espiritual": [
    {
      id: "port_esp_1",
      category: "body",
      label: "PRÁTICA",
      question: "Qual a profundidade da busca?",
      lowLabel: "Relaxamento",
      highLabel: "Vivência Ativa",
    },
    {
      id: "port_esp_2",
      category: "territory",
      label: "CONEXÃO",
      question: "Onde o corpo quer estar?",
      lowLabel: "Natureza/Grama",
      highLabel: "Templo Fechado",
    },
  ],
  "🎨 criativo / lifestyle": [
    {
      id: "port_cri_1",
      category: "body",
      label: "AÇÃO",
      question: "Qual é a dinâmica?",
      lowLabel: "Garimpar Lojas",
      highLabel: "Mão na Massa",
    },
    {
      id: "port_cri_2",
      category: "space",
      label: "CENÁRIO",
      question: "Onde a criatividade flui?",
      lowLabel: "Rua/Céu Aberto",
      highLabel: "Estúdio Fechado",
    },
  ],
  "🏛️ cultura": [
    {
      id: "port_cul_1",
      category: "territory",
      label: "TAMANHO",
      question: "Qual o escopo do passeio?",
      lowLabel: "Galeria Pequena",
      highLabel: "Museu Grande",
    },
    {
      id: "port_cul_2",
      category: "identity",
      label: "ACERVO",
      question: "Qual a sua fome estética?",
      lowLabel: "Arte Histórica",
      highLabel: "Contemporânea",
    },
  ],
  "🎒viagem curta": [
    {
      id: "port_via_1",
      category: "territory",
      label: "DESTINO",
      question: "Qual o chamado da natureza?",
      lowLabel: "Serra/Frio",
      highLabel: "Praia/Calor",
    },
    {
      id: "port_via_2",
      category: "body",
      label: "RITMO",
      question: "Como vai gastar a energia?",
      lowLabel: "Sombra e Água",
      highLabel: "Trilha/Aventura",
    },
  ],
  "🚩cilada": [
    {
      id: "cilada_1",
      category: "body",
      label: "Tolerância ao Caos",
      question: "Qual a sua tolerância para o caos hoje?",
      lowLabel: "Quero conforto",
      highLabel: "Sobrevivente nato",
    },
    {
      id: "cilada_2",
      category: "territory",
      label: "Logística de hoje",
      question: "Como você vai se mover?",
      lowLabel: "A pé / Uber",
      highLabel: "Estou de Carro",
    },
  ],
  "👨‍👩‍👧‍👦 família": [
    {
      id: "port_fam_1",
      category: "body",
      label: "ENERGIA",
      question: "Qual a energia das crianças/família hoje?",
      lowLabel: "Calma/Tranquila",
      highLabel: "Elétrica/Agitada",
    },
    {
      id: "port_fam_2",
      category: "space",
      label: "AMBIENTE",
      question: "Qual tipo de ambiente a família prefere?",
      lowLabel: "Ar Livre",
      highLabel: "Lugar Fechado",
    },
  ],
};

export const LOADING_PHRASES: Record<string, string[]> = {
  pt: [
    "Percebendo seu ritmo...",
    "Filtrando gemas para você...",
    "Consultando a cidade...",
    "Preparando suas revelações...",
    "⚠️ Cidades fora de SP, RJ e Floripa podem ter sugestões imprecisas.",
  ],
  en: [
    "Sensing your rhythm...",
    "Filtering gems for you...",
    "Consulting the city...",
    "Preparing your revelations...",
    "⚠️ Cities outside SP, RJ and Floripa may have imprecise suggestions.",
  ],
  es: [
    "Percibiendo tu ritmo...",
    "Filtrando gemas para ti...",
    "Consultando la ciudad...",
    "Preparando tus revelaciones...",
    "⚠️ Ciudades fuera de SP, RJ y Floripa pueden tener sugerencias imprecisas.",
  ],
};
